-- Broad starter seed for managed industry and career path taxonomy terms.
-- Safe to run multiple times because taxonomy_terms has a unique index on
-- (term_type, lower(trim(name))) and this script uses ON CONFLICT DO NOTHING.

INSERT INTO public.taxonomy_terms (term_type, name)
VALUES
  ('industry_tag', 'Agriculture and Agribusiness'),
  ('industry_tag', 'Arts and Culture'),
  ('industry_tag', 'Automotive Services'),
  ('industry_tag', 'Beauty and Wellness'),
  ('industry_tag', 'Business Process Outsourcing'),
  ('industry_tag', 'Cleaning and Janitorial Services'),
  ('industry_tag', 'Construction and Trades'),
  ('industry_tag', 'Creative and Design'),
  ('industry_tag', 'Customer Service'),
  ('industry_tag', 'Digital Services'),
  ('industry_tag', 'E-commerce and Online Selling'),
  ('industry_tag', 'Education and Training'),
  ('industry_tag', 'Energy and Utilities'),
  ('industry_tag', 'Entrepreneurship'),
  ('industry_tag', 'Environmental Services'),
  ('industry_tag', 'Finance and Accounting'),
  ('industry_tag', 'Food and Beverage'),
  ('industry_tag', 'Government and Public Service'),
  ('industry_tag', 'Healthcare and Wellness'),
  ('industry_tag', 'Hospitality and Tourism'),
  ('industry_tag', 'Human Resources and Administration'),
  ('industry_tag', 'Information Technology'),
  ('industry_tag', 'Insurance Services'),
  ('industry_tag', 'Legal and Compliance Services'),
  ('industry_tag', 'Logistics and Supply Chain'),
  ('industry_tag', 'Manufacturing and Production'),
  ('industry_tag', 'Media and Communications'),
  ('industry_tag', 'Office Administration'),
  ('industry_tag', 'Personal Services'),
  ('industry_tag', 'Property and Facilities Services'),
  ('industry_tag', 'Retail and Sales'),
  ('industry_tag', 'Safety and Security'),
  ('industry_tag', 'Social and Community Services'),
  ('industry_tag', 'Telecommunications'),
  ('industry_tag', 'Travel Services'),
  ('industry_tag', 'Transportation Services'),
  ('industry_tag', 'Wholesale and Distribution'),
  ('career_path', 'Administrative Assistant'),
  ('career_path', 'Administrative Officer'),
  ('career_path', 'Agribusiness Assistant'),
  ('career_path', 'Appointment Setter'),
  ('career_path', 'Auto Service Technician'),
  ('career_path', 'Back Office Associate'),
  ('career_path', 'Beauty Services Assistant'),
  ('career_path', 'Bookkeeping Assistant'),
  ('career_path', 'Brand and Content Assistant'),
  ('career_path', 'Call Center Agent'),
  ('career_path', 'Cashier'),
  ('career_path', 'Cleaner'),
  ('career_path', 'Collections Assistant'),
  ('career_path', 'Community Program Assistant'),
  ('career_path', 'Compliance Assistant'),
  ('career_path', 'Content Creator'),
  ('career_path', 'Construction Support Technician'),
  ('career_path', 'Costing Assistant'),
  ('career_path', 'Customer Service Associate'),
  ('career_path', 'Data Entry Clerk'),
  ('career_path', 'Delivery Coordinator'),
  ('career_path', 'Documentation Assistant'),
  ('career_path', 'Digital Marketing Assistant'),
  ('career_path', 'Digital Support Associate'),
  ('career_path', 'E-commerce Assistant'),
  ('career_path', 'Encoder'),
  ('career_path', 'Events Assistant'),
  ('career_path', 'Event and Hospitality Coordinator'),
  ('career_path', 'Executive Assistant'),
  ('career_path', 'Facilities Assistant'),
  ('career_path', 'Finance Assistant'),
  ('career_path', 'Food Preparation Assistant'),
  ('career_path', 'Food Service Crew'),
  ('career_path', 'Front Desk Associate'),
  ('career_path', 'Graphic Designer'),
  ('career_path', 'Guest Services Associate'),
  ('career_path', 'Help Desk Support Staff'),
  ('career_path', 'Hospitality Service Associate'),
  ('career_path', 'HR Assistant'),
  ('career_path', 'Inside Sales Representative'),
  ('career_path', 'Inventory Clerk'),
  ('career_path', 'IT Support Assistant'),
  ('career_path', 'Junior Bookkeeper'),
  ('career_path', 'Junior Recruiter'),
  ('career_path', 'Line Cook Assistant'),
  ('career_path', 'Logistics Coordinator'),
  ('career_path', 'Machine Operator'),
  ('career_path', 'Manufacturing Assistant'),
  ('career_path', 'Marketing Assistant'),
  ('career_path', 'Merchandising Assistant'),
  ('career_path', 'Mobile App Developer'),
  ('career_path', 'Office Clerk'),
  ('career_path', 'Office Staff'),
  ('career_path', 'Operations Assistant'),
  ('career_path', 'Payroll Assistant'),
  ('career_path', 'Personal Assistant'),
  ('career_path', 'Procurement Assistant'),
  ('career_path', 'Production Assistant'),
  ('career_path', 'Project Coordinator'),
  ('career_path', 'Property Admin Assistant'),
  ('career_path', 'Public Service Assistant'),
  ('career_path', 'Quality Assurance Assistant'),
  ('career_path', 'Receptionist'),
  ('career_path', 'Recruitment Assistant'),
  ('career_path', 'Records Assistant'),
  ('career_path', 'Retail Sales Associate'),
  ('career_path', 'Scheduling Assistant'),
  ('career_path', 'Safety Officer Assistant'),
  ('career_path', 'Sales Associate'),
  ('career_path', 'Sales Coordinator'),
  ('career_path', 'Service Advisor Assistant'),
  ('career_path', 'Service Crew'),
  ('career_path', 'Social Media Coordinator'),
  ('career_path', 'Social Media Assistant'),
  ('career_path', 'Store Assistant'),
  ('career_path', 'Talent Sourcing Assistant'),
  ('career_path', 'Technical Support Associate'),
  ('career_path', 'Telecom Support Associate'),
  ('career_path', 'Tour Coordinator Assistant'),
  ('career_path', 'Tourism Operations Assistant'),
  ('career_path', 'Trainer Assistant'),
  ('career_path', 'Transportation Coordinator'),
  ('career_path', 'Travel Desk Associate'),
  ('career_path', 'Virtual Assistant'),
  ('career_path', 'Warehouse Assistant'),
  ('career_path', 'Warehouse Coordinator'),
  ('career_path', 'Web Designer'),
  ('career_path', 'Web Developer'),
  ('career_path', 'Wellness Services Assistant'),
  ('career_path', 'Workforce Development Assistant'),
  ('career_path', 'Entrepreneur')
ON CONFLICT DO NOTHING;